// <auto-generated />
using System;
using EvaluacionP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaluacionP1.Migrations
{
    [DbContext(typeof(EvaluacionP1Context))]
    partial class EvaluacionP1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvaluacionP1.Models.Carrera", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("campus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreCarrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroSemestres")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("EvaluacionP1.Models.MBaquero", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarreraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("anio")
                        .HasColumnType("datetime2");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<double>("mensualidad")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("reprobo")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CarreraId");

                    b.ToTable("MBaquero");
                });

            modelBuilder.Entity("EvaluacionP1.Models.MBaquero", b =>
                {
                    b.HasOne("EvaluacionP1.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });
#pragma warning restore 612, 618
        }
    }
}
